// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBtawqMYj464lnGoVK5Jtt1PsFLopXcUfA",
    authDomain: "bloodfinder-bd.firebaseapp.com",
    projectId: "bloodfinder-bd",
    storageBucket: "bloodfinder-bd.firebasestorage.app",
    messagingSenderId: "119562024934",
    appId: "1:119562024934:web:374b79709415fa8a76c827",
    measurementId: "G-2VKV0WGT82",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRmHim0dgayyztopAd-nkjudvcud5IyCM',
    appId: '1:119562024934:android:bcf94482d8ce608c76c827',
    messagingSenderId: '119562024934',
    projectId: 'bloodfinder-bd',
    storageBucket: 'bloodfinder-bd.firebasestorage.app',
  );
}
