import '../../data/models/district.dart';

class AppDistricts {
  static const List<District> districts = [
    const District('Dhaka', [
      'Dhamrai',
      'Dohar',
      'Keraniganj',
      'Nawabganj',
      'Savar',
      'Tejgaon',
    ]),
    const District('Faridpur', [
      'Alfadanga',
      'Bhanga',
      'Boalmari',
      'Charbhadrasan',
      'Faridpur Sadar',
      'Madhukhali',
      'Nagarkanda',
      'Sadarpur',
      'Saltha',
    ]),
    const District('Gazipur', [
      'Gazipur Sadar',
      'Kaliakair',
      'Kaliganj',
      'Kapasia',
      'Sreepur',
    ]),
    const District('Gopalganj', [
      'Gopalganj Sadar',
      'Kashiani',
      'Kotalipara',
      'Muksudpur',
      'Tungipara',
    ]),
    const District('Kishoreganj', [
      'Austagram',
      'Bajitpur',
      'Bhairab',
      'Hossainpur',
      'Itna',
      'Karimganj',
      'Katiadi',
      'Kishoreganj Sadar',
      'Kuliarchar',
      'Mithamain',
      'Nikli',
      'Pakundia',
      'Tarail',
    ]),
    const District('Madaripur', ['Kalkini', 'Madaripur Sadar', 'Rajoir', 'Shibchar']),
    const District('Manikganj', [
      'Daulatpur',
      'Ghior',
      'Harirampur',
      'Manikganj Sadar',
      'Saturia',
      'Shibalaya',
      'Singair',
    ]),
    const District('Munshiganj', [
      'Gazaria',
      'Lohajang',
      'Munshiganj Sadar',
      'Sirajdikhan',
      'Sreenagar',
      'Tongibari',
    ]),
    const District('Narayanganj', [
      'Araihazar',
      'Bandar',
      'Narayanganj Sadar',
      'Rupganj',
      'Sonargaon',
    ]),
    const District('Narsingdi', [
      'Belabo',
      'Monohardi',
      'Narsingdi Sadar',
      'Palash',
      'Raipura',
      'Shibpur',
    ]),
    const District('Rajbari', [
      'Baliakandi',
      'Goalandaghat',
      'Kalukhali',
      'Pangsha',
      'Rajbari Sadar',
    ]),
    const District('Shariatpur', [
      'Bhedarganj',
      'Damudya',
      'Gosairhat',
      'Naria',
      'Palong',
      'Shariatpur Sadar',
    ]),
    const District('Tangail', [
      'Basail',
      'Bhuapur',
      'Delduar',
      'Dhanbari',
      'Ghatail',
      'Gopalpur',
      'Kalihati',
      'Madhupur',
      'Mirzapur',
      'Nagarpur',
      'Sakhipur',
      'Tangail Sadar',
    ]),
    const District('Bandarban', [
      'Alikadam',
      'Bandarban Sadar',
      'Lama',
      'Naikhongchhari',
      'Rowangchhari',
      'Ruma',
      'Thanchi',
    ]),
    const District('Brahmanbaria', [
      'Akhaura',
      'Bancharampur',
      'Brahmanbaria Sadar',
      'Kasba',
      'Nabinagar',
      'Nasirnagar',
      'Sarail',
      'Ashuganj',
    ]),
    const District('Chandpur', [
      'Chandpur Sadar',
      'Faridganj',
      'Haimchar',
      'Haziganj',
      'Kachua',
      'Matlab Dakkhin',
      'Matlab Uttar',
      'Shahrasti',
    ]),
    const District('Chittagong', [
      'Anwara',
      'Banshkhali',
      'Boalkhali',
      'Chandanaish',
      'Fatikchhari',
      'Hathazari',
      'Lohagara',
      'Mirsharai',
      'Patiya',
      'Rangunia',
      'Raozan',
      'Sandwip',
      'Satkania',
    ]),
    const District('Comilla', [
      'Barura',
      'Brahmanpara',
      'Burichang',
      'Chandina',
      'Chauddagram',
      'Daudkandi',
      'Debidwar',
      'Homna',
      'Laksam',
      'Meghna',
      'Muradnagar',
      'Nangalkot',
      'Titas',
    ]),
    const District('Cox\'s Bazar', [
      'Chakaria',
      'Cox\'s Bazar Sadar',
      'Kutubdia',
      'Maheshkhali',
      'Pekua',
      'Ramu',
      'Teknaf',
      'Ukhiya',
    ]),
    const District('Feni', [
      'Chhagalnaiya',
      'Daganbhuiyan',
      'Feni Sadar',
      'Fulgazi',
      'Parshuram',
      'Sonagazi',
    ]),
    const District('Khagrachari', [
      'Dighinala',
      'Khagrachhari Sadar',
      'Lakshmichhari',
      'Mahalchhari',
      'Manikchhari',
      'Matiranga',
      'Panchhari',
      'Ramgarh',
      'Guimara',
    ]),
    const District('Lakshmipur', [
      'Lakshmipur Sadar',
      'Raipur',
      'Ramganj',
      'Ramgati',
      'Kamalnagar',
    ]),
    const District('Noakhali', [
      'Begumganj',
      'Chatkhil',
      'Companiganj',
      'Hatia',
      'Kabirhat',
      'Noakhali Sadar',
      'Senbagh',
      'Subarnachar',
    ]),
    const District('Rangamati', [
      'Baghaichhari',
      'Barkal',
      'Belaichhari',
      'Juraichhari',
      'Kaptai',
      'Kawkhali',
      'Langadu',
      'Naniarchar',
      'Rajasthali',
      'Rangamati Sadar',
    ]),
    const District('Bagerhat', [
      'Bagerhat Sadar',
      'Chitalmari',
      'Fakirhat',
      'Kachua',
      'Mollahat',
      'Mongla',
      'Morrelganj',
      'Rampal',
      'Sarankhola',
    ]),
    const District('Chuadanga', [
      'Alamdanga',
      'Chuadanga Sadar',
      'Damurhuda',
      'Jibannagar',
    ]),
    const District('Jessore', [
      'Abhaynagar',
      'Bagherpara',
      'Chaugachha',
      'Jhikargachha',
      'Keshabpur',
      'Manirampur',
      'Jessore Sadar',
      'Sharsha',
    ]),
    const District('Jhenaidah', [
      'Harinakunda',
      'Jhenaidah Sadar',
      'Kaliganj',
      'Kotchandpur',
      'Maheshpur',
      'Shailkupa',
    ]),
    const District('Khulna', [
      'Batiaghata',
      'Dacope',
      'Dumuria',
      'Dighalia',
      'Koyra',
      'Paikgacha',
      'Phultala',
      'Rupsha',
      'Terokhada',
    ]),
    const District('Kushtia', [
      'Bheramara',
      'Daulatpur',
      'Khoksa',
      'Kumarkhali',
      'Kushtia Sadar',
      'Mirpur',
    ]),
    const District('Magura', ['Magura Sadar', 'Mohammadpur', 'Shalikha', 'Sreepur']),
    const District('Meherpur', ['Gangni', 'Meherpur Sadar', 'Mujibnagar']),
    const District('Narail', ['Kalia', 'Lohagara', 'Narail Sadar']),
    const District('Satkhira', [
      'Assasuni',
      'Debhata',
      'Kaliganj',
      'Kalaroa',
      'Satkhira Sadar',
      'Shyamnagar',
      'Tala',
    ]),
    const District('Bogra', [
      'Adamdighi',
      'Bogra Sadar',
      'Dhunat',
      'Dupchanchia',
      'Gabtali',
      'Kahaloo',
      'Nandigram',
      'Sariakandi',
      'Shajahanpur',
      'Sherpur',
      'Shibganj',
      'Sonatala',
    ]),
    const District('Chapainawabganj', [
      'Bholahat',
      'Gomastapur',
      'Nachole',
      'Nawabganj Sadar',
      'Shibganj',
    ]),
    const District('Dinajpur', [
      'Birampur',
      'Birganj',
      'Biral',
      'Bochaganj',
      'Chirirbandar',
      'Dinajpur Sadar',
      'Ghoraghat',
      'Hakimpur',
      'Kaharole',
      'Khansama',
      'Nawabganj',
      'Parbatipur',
    ]),
    const District('Joypurhat', [
      'Akkelpur',
      'Joypurhat Sadar',
      'Kalai',
      'Khetlal',
      'Panchbibi',
    ]),
    const District('Naogaon', [
      'Atrai',
      'Badalgachhi',
      'Dhamoirhat',
      'Manda',
      'Mahadebpur',
      'Naogaon Sadar',
      'Niamatpur',
      'Patnitala',
      'Porsha',
      'Raninagar',
      'Sapahar',
    ]),
    const District('Natore', [
      'Bagatipara',
      'Baraigram',
      'Gurudaspur',
      'Lalpur',
      'Natore Sadar',
      'Singra',
    ]),
    const District('Pabna', [
      'Atgharia',
      'Bera',
      'Bhangura',
      'Chatmohar',
      'Faridpur',
      'Ishwardi',
      'Pabna Sadar',
      'Santhia',
      'Sujanagar',
    ]),
    const District('Rajshahi', [
      'Bagha',
      'Bagmara',
      'Charghat',
      'Durgapur',
      'Godagari',
      'Mohanpur',
      'Paba',
      'Puthia',
      'Tanore',
    ]),
    const District('Sirajganj', [
      'Belkuchi',
      'Chauhali',
      'Kamarkhanda',
      'Kazipur',
      'Raiganj',
      'Shahjadpur',
      'Sirajganj Sadar',
      'Tarash',
      'Ullapara',
    ]),
    const District('Barguna', [
      'Amtali',
      'Bamna',
      'Barguna Sadar',
      'Betagi',
      'Patharghata',
      'Taltali',
    ]),
    const District('Barisal', [
      'Agailjhara',
      'Babuganj',
      'Bakerganj',
      'Banaripara',
      'Barisal Sadar',
      'Gournadi',
      'Hizla',
      'Mehendiganj',
      'Muladi',
    ]),
    const District('Bhola', [
      'Bhola Sadar',
      'Borhanuddin',
      'Char Fasson',
      'Daulatkhan',
      'Lalmohan',
      'Manpura',
      'Tazumuddin',
    ]),
    const District('Jhalokathi', [
      'Jhalokathi Sadar',
      'Kathalia',
      'Nalchity',
      'Rajapur',
    ]),
    const District('Patuakhali', [
      'Bauphal',
      'Dashmina',
      'Dumki',
      'Galachipa',
      'Kalapara',
      'Mirzaganj',
      'Patuakhali Sadar',
      'Rangabali',
    ]),
    const District('Pirojpur', [
      'Bhandaria',
      'Kawkhali',
      'Mathbaria',
      'Nazirpur',
      'Nesarabad (Swarupkathi)',
      'Pirojpur Sadar',
      'Zianagar',
    ]),
    const District('Jamalpur', [
      'Bakshiganj',
      'Dewanganj',
      'Islampur',
      'Jamalpur Sadar',
      'Madarganj',
      'Melandaha',
      'Sarishabari',
    ]),
    const District('Mymensingh', [
      'Bhaluka',
      'Dhobaura',
      'Fulbaria',
      'Gaffargaon',
      'Gauripur',
      'Haluaghat',
      'Ishwarganj',
      'Mymensingh Sadar',
      'Muktagacha',
      'Nandail',
      'Phulpur',
      'Trishal',
    ]),
    const District('Netrokona', [
      'Atpara',
      'Barhatta',
      'Durgapur',
      'Kalmakanda',
      'Kendua',
      'Madan',
      'Mohanganj',
      'Netrokona Sadar',
      'Purbadhala',
    ]),
    const District('Sherpur', [
      'Jhenaigati',
      'Nakla',
      'Nalitabari',
      'Sherpur Sadar',
      'Sreebardi',
    ]),
    const District('Habiganj', [
      'Ajmiriganj',
      'Bahubal',
      'Baniachang',
      'Chunarughat',
      'Habiganj Sadar',
      'Lakhai',
      'Madhabpur',
      'Nabiganj',
      'Shayestaganj',
    ]),
    const District('Moulvibazar', [
      'Barlekha',
      'Juri',
      'Kamalganj',
      'Kulaura',
      'Moulvibazar Sadar',
      'Rajnagar',
      'Sreemangal',
    ]),
    const District('Sunamganj', [
      'Bishwamvarpur',
      'Chhatak',
      'Dharampasha',
      'Dirai',
      'Dowarabazar',
      'Jagannathpur',
      'Jamalganj',
      'Sulla',
      'Sunamganj Sadar',
      'Tahirpur',
    ]),
    const District('Sylhet', [
      'Balaganj',
      'Beanibazar',
      'Bishwanath',
      'Companiganj',
      'Fenchuganj',
      'Golapganj',
      'Jaintiapur',
      'Kanaighat',
      'Sylhet Sadar',
    ]),
    const District('Gaibandha', [
      'Fulchhari',
      'Gaibandha Sadar',
      'Gobindaganj',
      'Palashbari',
      'Sadullapur',
      'Saghata',
      'Sundarganj',
    ]),
    const District('Kurigram', [
      'Bhurungamari',
      'Char Rajibpur',
      'Chilmari',
      'Kurigram Sadar',
      'Nageshwari',
      'Phulbari',
      'Rajarhat',
      'Raomari',
      'Ulipur',
    ]),
    const District('Lalmonirhat', [
      'Aditmari',
      'Hatibandha',
      'Kaliganj',
      'Lalmonirhat Sadar',
      'Patgram',
    ]),
    const District('Nilphamari', [
      'Dimla',
      'Domar',
      'Jaldhaka',
      'Kishoreganj',
      'Nilphamari Sadar',
      'Saidpur',
    ]),
    const District('Panchagarh', [
      'Atwari',
      'Boda',
      'Debiganj',
      'Panchagarh Sadar',
      'Tetulia',
    ]),
    const District('Rangpur', [
      'Badarganj',
      'Gangachara',
      'Kaunia',
      'Mithapukur',
      'Pirgachha',
      'Pirganj',
      'Rangpur Sadar',
      'Taraganj',
    ]),
    const District('Thakurgaon', [
      'Baliadangi',
      'Haripur',
      'Pirganj',
      'Ranisankail',
      'Thakurgaon Sadar',
    ]),
  ];
}
